# Generated by Django 6.0 on 2026-02-28 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_date_joined_and_more'),
        ('billing', '0002_wasteplan_wasteserviceprovider_wasteproviderward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='wastecoverage',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.wasteblock'),
        ),
        migrations.CreateModel(
            name='WasteBlockProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_map', to='billing.wasteblock')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='billing.wasteserviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='WasteWardMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_metas', to='billing.wasteblock')),
                ('ward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waste_meta', to='accounts.ward')),
            ],
        ),
        migrations.DeleteModel(
            name='WasteProviderWard',
        ),
    ]
