# Generated by Django 6.0 on 2026-03-02 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_date_joined_and_more'),
        ('billing', '0003_wasteblock_wastecoverage_block_wasteblockprovider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CONSUMER_STAPLE', 'Consumer Staple'), ('INDUSTRY_SERVICES', 'Industry / Services'), ('FINANCIAL_SERVICES', 'Financial Services'), ('HEALTH_EDUCATION', 'Health / Education'), ('HOSPITALITY', 'Hospitality'), ('OTHER', 'Other')], max_length=40)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('national_reg_number', models.CharField(blank=True, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ward')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessLicenseDemandNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_number', models.CharField(max_length=60)),
                ('license_year', models.PositiveIntegerField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='SUBMITTED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_license_notice', to='billing.bill')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_notices', to='billing.business')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_license_notices', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_business_license_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('notice_number', 'license_year')},
            },
        ),
    ]
